### ISSUE TITLE
version 0.1.2?

### ISSUE THREAD

**Issue by SethTisue** [lihaoyi/geny#3]
there is a version 0.1.2 on Maven Central, and you even depend on it in the Ammonite build, but there's doesn't seem to be any trace of it here — no tag or release, no post 0.1.1 commits...?

**Comment by SethTisue** [comment]
the context for why I want to know is, I'm trying to add Ammonite to the community build (we had ammonite-ops already, I'm trying to add the rest), and I'm getting a compile error in `amm/runtime/src/main/scala/ammonite/runtime/tools/Tools.scala` that's reproducible by downgrading Ammonite's geny dependency to 0.1.1

so I need 0.1.2 in the community build in order to add Ammonite, but where is it?

**Comment by lihaoyi** [comment]
Looks like I forgot to push it. Here it is... https://github.com/lihaoyi/geny/commit/a9ca9e96c6752d0bf57bcfe77cea15f31c2fa09f

**Comment by SethTisue** [comment]
thank you!
